import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/component/base/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "케이쉴드주니어",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className + "flex h-full w-full flex-col"}>
        <Header />
        {children}
      </body>
    </html>
  );
}
